/* DO NOT EDIT THIS FILE - it is machine generated */
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <string.h>
#include <jni.h>
#define TEST_RS232_CMD_APLEX          66
#define TEST_RS485_CMD_APLEX          67
#define TEST_RS422_CMD_APLEX          68
#define TEST_LOOPBACK_CMD_APLEX       69

#include "android/log.h"
static const char *TAG="com3mode";
#define LOGE(fmt, args...) __android_log_print(ANDROID_LOG_ERROR, TAG, fmt, ##args)

void com3mode_ioctl ( int cmd ) {
    int fd = open ( "/dev/com3mode", O_RDWR );
    if ( fd < 0 ) {
        LOGE ( "can't open com3mode file." );
        return;
    }

    ioctl ( fd, cmd, 0 );
    close ( fd );
}

/* Header for class com_android_com3mode_COM3Mode */

/*
 * Class:     com_android_com3mode_COM3Mode
 * Method:    setRS232Mode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aplex_aplextest_jninative_COM3Mode_setRS232Mode
        (JNIEnv * env, jclass clazz) {
    com3mode_ioctl(TEST_RS232_CMD_APLEX);
}

/*
 * Class:     com_android_com3mode_COM3Mode
 * Method:    setRS485Mode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aplex_aplextest_jninative_COM3Mode_setRS485Mode
        (JNIEnv * env, jclass clazz) {
    com3mode_ioctl(TEST_RS485_CMD_APLEX);
}

/*
 * Class:     com_android_com3mode_COM3Mode
 * Method:    setRS422Mode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aplex_aplextest_jninative_COM3Mode_setRS422Mode
        (JNIEnv * env, jclass clazz) {
    com3mode_ioctl(TEST_RS422_CMD_APLEX);
}

/*
 * Class:     com_android_com3mode_COM3Mode
 * Method:    setLoopBackMode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aplex_aplextest_jninative_COM3Mode_setLoopBackMode
        (JNIEnv * env, jclass clazz) {
    com3mode_ioctl(TEST_LOOPBACK_CMD_APLEX);
}

