/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aplex_aplextest_jninative_COM3Mode */

#ifndef _Included_com_aplex_aplextest_jninative_COM3Mode
#define _Included_com_aplex_aplextest_jninative_COM3Mode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aplex_aplextest_jninative_COM3Mode
 * Method:    setRS232Mode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aplex_aplextest_jninative_COM3Mode_setRS232Mode
  (JNIEnv *, jclass);

/*
 * Class:     com_aplex_aplextest_jninative_COM3Mode
 * Method:    setRS485Mode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aplex_aplextest_jninative_COM3Mode_setRS485Mode
  (JNIEnv *, jclass);

/*
 * Class:     com_aplex_aplextest_jninative_COM3Mode
 * Method:    setRS422Mode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aplex_aplextest_jninative_COM3Mode_setRS422Mode
  (JNIEnv *, jclass);

/*
 * Class:     com_aplex_aplextest_jninative_COM3Mode
 * Method:    setLoopBackMode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aplex_aplextest_jninative_COM3Mode_setLoopBackMode
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
