/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aplex_aplextest_jninative_StabilityTest */

#ifndef _Included_com_aplex_aplextest_jninative_StabilityTest
#define _Included_com_aplex_aplextest_jninative_StabilityTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aplex_aplextest_jninative_StabilityTest
 * Method:    StartMestTest
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_aplex_aplextest_jninative_StabilityTest_StartMestTest
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_aplex_aplextest_jninative_StabilityTest
 * Method:    StopMemTest
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aplex_aplextest_jninative_StabilityTest_StopMemTest
  (JNIEnv *, jobject);

/*
 * Class:     com_aplex_aplextest_jninative_StabilityTest
 * Method:    getPercent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aplex_aplextest_jninative_StabilityTest_getPercent
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
