/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdlib.h>
#include <android/log.h>
#include "memtest.c"
#include "com_aplex_aplextest_jninative_StabilityTest.h"

/*
 * Class:     com_aplex_aplextest_jninative_StabilityTest
 * Method:    memtest1
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_aplex_aplextest_jninative_StabilityTest_StartMestTest
  (JNIEnv *env, jobject obj, jint size){
	return memtest(size);
}

/*
 * Class:     com_aplex_aplextest_jninative_StabilityTest
 * Method:    StopMemTest
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aplex_aplextest_jninative_StabilityTest_StopMemTest
  (JNIEnv *env, jobject obj){
	gotoout(1);
	return 1;
}

/*
 * Class:     com_aplex_aplextest_jninative_StabilityTest
 * Method:    getPercent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aplex_aplextest_jninative_StabilityTest_getPercent
  (JNIEnv *env, jobject obj){
	return getpercent();
}

